### ISSUE TITLE
multiple rtsp sources?

### ISSUE THREAD

**Issue by zhoujiuyi** [JoeKeikun/jsmpeg_md_cn#1]
How to achieve multiple rtsp sources?

**Comment by JoeKeikun** [comment]
> How to achieve multiple rtsp sources?

抱歉，在我的项目里主要是用JSMpeg来解决安卓设备的视频内联播放的问题，所以播放ts文件功能就满足交互的需求了。至于JSMpeg提供的流式传输播放模式，我暂时还没有尝试。

为何你需要使用多路流式源？

如果是多个窗体播放不同的视频：
【方法1】可以尝试下多创建几个JSMpeg的实例来展示内容（但是会给机器CPU带来一定的计算压力，因为需要实时解析运算）
【方法2】使用ffmpeg合并视屏，大致逻辑参照：https://blog.csdn.net/weiwen12138/article/details/70344681

如果是单个窗体播放重叠的视频：
建议还是在ffmpeg视频处理阶段攻克这个问题，让前端保持单窗体播放（毕竟现在服务端的计算力远大于前端设备）
