### ISSUE TITLE
流式传输时，poster属性设置无效（When streaming transmission,the poster is bad）

### ISSUE THREAD

**Issue by 3030811865** [JoeKeikun/jsmpeg_md_cn#2]
贴出代码：
var player = new JSMpeg.Player(url, {canvas: can,poster: 'img/timg.gif'});

**Comment by JoeKeikun** [comment]
@3030811865  在源码src/video-element.js里有具体逻辑(63行)：

`	// Setup the poster element, if any`
`	if (options.poster && !options.autoplay && !this.player.options.streaming) {`
`		options.decodeFirstFrame = false;`
`		this.poster = new Image();`
`		this.poster.src = options.poster;`
`               ...`
`	}`

poster只有在autoplay:false（非自动播放） && streaming:false（非流式）的情况下使用
